# Jekyll will exclude these files during compilation
exclude:
  - README.md
  - TERMS.md
  - LICENSE

# Whether or not to include docs that are marked as preview
includePreviews: true

# Markdown parsing configuration
markdown: kramdown
kramdown:
  auto_ids: true
  parse_block_html: true

# All links in the design library will start with this baseurl
baseurl: "/designpatterns"

# The url for the home page of the design library
homeurl: "/designpatterns"

# Set the default layout for everything in the categories folder to _layouts/default.html
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"

# All email links will use this variable
email: contactUXD@uspto.gov?subject=USPTO UI Design Library

# Repository information, which is used for links like "View on Github"
repository:
  name: uspto/designpatterns
  url: https://github.com/uspto/designpatterns

sections:
  - foundation
  - components
  - patterns
  - inspiration

collections:
  releases:
    output: true
    permalink: /v/:path
  assets:
    output: true
    permalink: /dist/:path