
# All email links will use this variable
email: contactUXD@uspto.gov?subject=USPTO UI Design Library

# Repository information, which is used for links like "View on Github"
repository:
  name: uspto/designpatterns
  url: https://github.com/uspto/designpatterns

# Whether or not to include docs that are marked as preview
includePreviews: true

# All links in the design library will start with this baseurl
baseurl: "/designpatterns"

# The url for the home page of the design library
homeurl: "/designpatterns"

# Makes it so that generated page urls will not end with .html
permalink: :path

staticurl: https://static.scania.com/cds/awinny/tmp

# Markdown parsing configuration
markdown: kramdown
kramdown:
  auto_ids: true
  parse_block_html: true

# Set the default layout for everything in the categories folder to _layouts/default.html
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"

# Sections are kept here to be able to set render order
sections:
  - foundation
  - components
  - patterns
  - inspiration

# Jekyll will exclude these files during compilation
exclude:
  - README.md
  - TERMS.md
  - LICENSE

# Setting for releases output structure
collections:
  releases:
    output: true
    permalink: /v/:path
  assets:
    output: true
    permalink: /dist/:path