
# All email links will use this variable
email: contactUXD@uspto.gov?subject=USPTO UI Design Library

# Repository information, which is used for links like "View on Github"
repository:
  name: uspto/ux-library
  url: https://github.com/uspto/ux-library

# All links in the design library will start with this baseurl
baseurl: "/ux-library"

# The url for the home page of the design library
homeurl: "/ux-library"

mode: app

brand: scania

staticurl: https://static.scania.com/cds/awinny/tmp

# Markdown parsing configuration
markdown: kramdown
kramdown:
  auto_ids: true
  parse_block_html: true

# Jekyll will exclude these files during compilation
exclude:
  - README.md
  - TERMS.md
  - LICENSE

# Setting for releases output structure
collections:
  pages:
    permalink: /:path
  releases:
    permalink: /v/:path
  api:
    output: true
    permalink: /api/:path/index:output_ext
  assets:
    output: true
    permalink: /dist/:path